name: AI Content & Code Detection

on: [push, pull_request]

jobs:
    detect-ai-code:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "day 21" # 👈 Change working dir relative to repo root
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Full git history

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install ai-gen-code-search
              run: |
                  pip install ai-gen-code-search

            - name: Run AI Code Detection
              run: |
                  ai-gen-code-search scan . > ai-detection-report.txt || true

            - name: Upload report
              uses: actions/upload-artifact@v4
              with:
                  name: ai-detection-report
                  path: ai-detection-report.txt
