name: Codequiry Check

on:
    push:
        branches:
            - main
            - "student/*"

jobs:
    check_code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - name: Install Codequiry CLI
              run: |
                  pip install codequiry

            - name: Run Codequiry
              run: |
                  codequiry check --folder ./ --apikey ${{ secrets.CODEQUIRY_API_KEY }} --report report.json

            - name: Upload Report
              uses: actions/upload-artifact@v4
              with:
                  name: codequiry-report
                  path: report.json
